install.packages(c("dplyr",
                   "tidyr",
                   "readr",
                   "stringr",
                   "ggplot2",
                   "igraph",
                   "quanteda",
                   "quanteda.textplots",
                   "quanteda.textstats"))